package com.perfectlimited.ezypay.model;

/**
 */
public class ModelEvent {
 private long  COLUMN_EVENTS_ID=0;
 private   String COLUMN_EVENTS_NAME="";
 private String COLUMN_EVENTS_DESCRIPTION="";
 private String COLUMN_EVENTS_EVENTON="";
 private String COLUMN_EVENTS_EVENTATFROM="";
 private  String COLUMN_EVENTS_EVENTATTO="";


 public long getCOLUMN_EVENTS_ID() {
  return COLUMN_EVENTS_ID;
 }

 public void setCOLUMN_EVENTS_ID(long COLUMN_EVENTS_ID) {
  this.COLUMN_EVENTS_ID = COLUMN_EVENTS_ID;
 }

 public String getCOLUMN_EVENTS_NAME() {
  return COLUMN_EVENTS_NAME;
 }

 public void setCOLUMN_EVENTS_NAME(String COLUMN_EVENTS_NAME) {
  this.COLUMN_EVENTS_NAME = COLUMN_EVENTS_NAME;
 }

 public String getCOLUMN_EVENTS_DESCRIPTION() {
  return COLUMN_EVENTS_DESCRIPTION;
 }

 public void setCOLUMN_EVENTS_DESCRIPTION(String COLUMN_EVENTS_DESCRIPTION) {
  this.COLUMN_EVENTS_DESCRIPTION = COLUMN_EVENTS_DESCRIPTION;
 }

 public String getCOLUMN_EVENTS_EVENTON() {
  return COLUMN_EVENTS_EVENTON;
 }

 public void setCOLUMN_EVENTS_EVENTON(String COLUMN_EVENTS_EVENTON) {
  this.COLUMN_EVENTS_EVENTON = COLUMN_EVENTS_EVENTON;
 }

 public String getCOLUMN_EVENTS_EVENTATFROM() {
  return COLUMN_EVENTS_EVENTATFROM;
 }

 public void setCOLUMN_EVENTS_EVENTATFROM(String COLUMN_EVENTS_EVENTATFROM) {
  this.COLUMN_EVENTS_EVENTATFROM = COLUMN_EVENTS_EVENTATFROM;
 }

 public String getCOLUMN_EVENTS_EVENTATTO() {
  return COLUMN_EVENTS_EVENTATTO;
 }

 public void setCOLUMN_EVENTS_EVENTATTO(String COLUMN_EVENTS_EVENTATTO) {
  this.COLUMN_EVENTS_EVENTATTO = COLUMN_EVENTS_EVENTATTO;
 }
}
